baseURL = '/'
languageCode = 'zh-CN'
title = 'æ¨ç¥–æ”€'
disableKinds = ['taxonomy', 'term']
minify = true
publishDir = 'public'

[params]
    subTitle = 'ä¸ªäººä¸»é¡µ'
    keywords = 'æ¨ç¥–æ”€,æ¨æ”€,ç¥–æ”€,é˜¿æ”€,ä¸ªäººä¸»é¡µ,ä¸ªäººç½‘ç«™'
    description = 'æ¨ç¥–æ”€ï¼Œä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…ã€‚'
    avatar = '/img/avatar.jpg'
    siteName = 'æ¨ç¥–æ”€'
    siteDescription = 'ä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…'

[params.main.intro]
    title = 'æˆ‘å« æ¨ç¥–æ”€'
    subTitle = 'ä½ å¥½ï¼Œå¾ˆé«˜å…´è®¤è¯†ä½ ğŸ‘‹'
    description = 'ä¸€ä¸ªæ­£åœ¨ä¸æ–­å­¦ä¹ ï¼Œä¸æ–­è¿›æ­¥çš„åˆ›ä¸šè€…'
    bgImg = '/img/me.jpg'

[[params.main.card]]
    title = 'å­¦ä¹ '
    subTitle = 'çˆ±å¥½'
    description = 'å¥½å¥½å­¦ä¹ ï¼Œå¤©å¤©å‘ä¸Š'
    bgImg = '/img/01.jpg'
    butText = 'æŸ¥çœ‹'
    butLink = ''

[[params.main.card]]
    title = 'ç¼–ç¨‹'
    subTitle = 'çˆ±å¥½'
    description = 'ç¼–ç¨‹ï¼Œè®©ç”Ÿæ´»æ›´åŠ ç¾å¥½'
    bgImg = '/img/02.jpg'
    butText = 'æŸ¥çœ‹'
    butLink = ''

[[params.main.card]]
    title = 'æŠ˜è…¾'
    subTitle = 'çˆ±å¥½'
    description = 'ç”Ÿå‘½ä¸æ¯ï¼ŒæŠ˜è…¾ä¸æ­¢ã€‚'
    bgImg = '/img/03.jpg'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'æ—…è¡Œ'
    subTitle = 'çˆ±å¥½'
    description = 'çœ‹ä¸åŒçš„æ™¯ï¼Œä½“ä¼šä¸ä¸€æ ·çš„äººç”Ÿã€‚'
    bgImg = '/img/04.jpg'
    butText = 'æŸ¥çœ‹'
    butLink = ''



[params.footer]
    startDate = 2021
    #icp = 'æ»‡ICPå¤‡2021007697å·-11'
[params.footer.police]
    #number = 53038102530444
    text = 'æ»‡å…¬ç½‘å®‰å¤‡ 53038102530444 å·'

