baseURL = 'https://www.yangzupan.com/'
languageCode = 'zh-CN'
title = 'æ¨ç¥–æ”€'
disableKinds = ['taxonomy', 'term']
minify = true
publishDir = 'public1'

[params]
    subTitle = 'ä¸ªäººä¸»é¡µ'
    keywords = 'æ¨ç¥–æ”€,æ¨æ”€,ç¥–æ”€,é˜¿æ”€,ä¸ªäººä¸»é¡µ,ä¸ªäººç½‘ç«™'
    description = 'æ¨ç¥–æ”€ï¼Œä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…ã€‚'
    avatar = 'https://cdn.yangzupan.com/images/home/avatar.jpg!default'
    siteName = 'æ¨ç¥–æ”€'
    siteDescription = 'ä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…'

[[params.head.cssFile]]
    link = ''

[params.main.intro]
    title = 'æˆ‘å«'
    subTitle = 'ä½ å¥½ï¼Œå¾ˆé«˜å…´è®¤è¯†ä½ ğŸ‘‹'
    description = 'ä¸€ä¸ªæ­£åœ¨ä¸æ–­å­¦ä¹ ï¼Œä¸æ–­è¿›æ­¥çš„åˆ›ä¸šè€…'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/me.jpg!default'

[[params.main.card]]
    title = 'å­¦ä¹ '
    subTitle = 'çˆ±å¥½'
    description = 'å¥½å¥½å­¦ä¹ ï¼Œå¤©å¤©å‘ä¸Š'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/01.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'ç¼–ç¨‹'
    subTitle = 'çˆ±å¥½'
    description = 'ç¼–ç¨‹ï¼Œè®©ç”Ÿæ´»æ›´åŠ ç¾å¥½'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/02.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'æŠ˜è…¾'
    subTitle = 'çˆ±å¥½'
    description = 'ç”Ÿå‘½ä¸æ¯ï¼ŒæŠ˜è…¾ä¸æ­¢ã€‚'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/03.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'æ—…è¡Œ'
    subTitle = 'çˆ±å¥½'
    description = 'çœ‹ä¸åŒçš„æ™¯ï¼Œä½“ä¼šä¸ä¸€æ ·çš„äººç”Ÿã€‚'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/04.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''

[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/flowbite/2.3.0/flowbite.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/wesome-qr/2.1.5-rc.0/awesome-qr.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/html2canvas/html2canvas.min.js'
[[params.foot.jsFile]]
    link = ''
    
[params.footer]
    startDate = 2021
    icp = 'æ»‡ICPå¤‡2021007697å·-11'
[params.footer.police]
    number = 53038102530444
    text = 'æ»‡å…¬ç½‘å®‰å¤‡ 53038102530444 å·'

