baseURL = 'https://www.yangzupan.com/'
languageCode = 'zh-CN'
title = 'æ¨ç¥–æ”€'
disableKinds = ['taxonomy', 'term']
minify = true
publishDir = 'public1'

[params]
    subTitle = 'ä¸ªäººä¸»é¡µ'
    keywords = 'æ¨ç¥–æ”€,æ¨æ”€,ç¥–æ”€,é˜¿æ”€,ä¸ªäººä¸»é¡µ,ä¸ªäººç½‘ç«™'
    description = 'æ¨ç¥–æ”€ï¼Œä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…ã€‚'
    avatar = 'https://cdn.yangzupan.com/images/home/avatar.webp!default'
    siteName = 'æ¨ç¥–æ”€'
    siteDescription = 'ä¸€ä¸ªæ­£åœ¨æˆé•¿ã€ä¸æ–­è¿›åŒ–ã€æŒç»­å­¦ä¹ çš„ä¹äº”ååˆ›ä¸šè€…'

[[params.head.cssFile]]

[[params.head.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/fontawesome/6.5.2/js/brands.min.js'
[[params.head.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/fontawesome/6.5.2/js/solid.min.js'
[[params.head.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/fontawesome/6.5.2/js/fontawesome.min.js'

[params.main.intro]
    title = 'æˆ‘å«'
    subTitle = 'ä½ å¥½ï¼Œå¾ˆé«˜å…´è®¤è¯†ä½ ğŸ‘‹'
    description = 'ä¸€ä¸ªæ­£åœ¨ä¸æ–­å­¦ä¹ ï¼Œä¸æ–­è¿›æ­¥çš„åˆ›ä¸šè€…'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/me.jpg!default'

[[params.main.card]]
    title = 'å­¦ä¹ '
    subTitle = 'çˆ±å¥½'
    description = 'å¥½å¥½å­¦ä¹ ï¼Œå¤©å¤©å‘ä¸Š'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/01.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'ç¼–ç¨‹'
    subTitle = 'çˆ±å¥½'
    description = 'ç¼–ç¨‹ï¼Œè®©ç”Ÿæ´»æ›´åŠ ç¾å¥½'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/02.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'æŠ˜è…¾'
    subTitle = 'çˆ±å¥½'
    description = 'ç”Ÿå‘½ä¸æ¯ï¼ŒæŠ˜è…¾ä¸æ­¢ã€‚'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/03.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''
[[params.main.card]]
    title = 'æ—…è¡Œ'
    subTitle = 'çˆ±å¥½'
    description = 'çœ‹ä¸åŒçš„æ™¯ï¼Œä½“ä¼šä¸ä¸€æ ·çš„äººç”Ÿã€‚'
    bgImg = 'https://cdn.yangzupan.com/images/home/bg/04.jpg!default'
    butText = 'æŸ¥çœ‹'
    butLink = ''

    
[params.footer.contact]
    [[params.footer.contact.list]]
        name = 'é‚®ç®±'
        icon = 'fa-solid fa-envelope'
        link = 'mailto:www@yangzupan.com'
    [[params.footer.contact.list]]
        name = 'å¾®ä¿¡äºŒç»´ç '
        icon = 'fa-brands fa-weixin'
        isQrCode = false # äºŒç»´ç å¿…é¡»æœ‰id
        id = 'wx'
        direction = '' # top,
        link = 'https://cdn.yangzupan.com/images/public/qrcode/social/wx.svg'
    [[params.footer.contact.list]]
        name = 'qq'
        icon = 'fa-brands fa-qq'
        link = 'https://qm.qq.com/q/U5A4EIlGkG'
    [[params.footer.contact.list]]
        name = 'Github'
        icon = 'fa-brands fa-github'
        link = 'https://github.com/yangzupan'
    [[params.footer.contact.list]]
        name = 'Gitee'
        icon = 'fa-solid fa-code-branch'
        link = 'https://gitee.com/yangzupan'
    [[params.footer.contact.list]]
        name = 'Bç«™'
        icon = 'fa-brands fa-bilibili'
        link = 'https://space.bilibili.com/382569208'
    [[params.footer.contact.list]]
        name = 'æŠ–éŸ³'
        icon = 'fa-brands fa-tiktok'
        link = 'https://v.douyin.com/idW8pXtW/'
    [[params.footer.contact.list]]
        name = 'å¾®åš'
        icon = 'fa-brands fa-weibo'
        link = 'https://weibo.com/yangzupan'
    [[params.footer.contact.list]]
        name = 'çŸ¥ä¹'
        icon = 'fa-brands fa-zhihu'
        link = 'https://www.zhihu.com/people/yangzupan'

[params.footer.copyright]
    startDate = 2021
    icp = 'æ»‡ICPå¤‡2021007697å·-11'
    police.number = 53038102530444
    police.text = 'æ»‡å…¬ç½‘å®‰å¤‡ 53038102530444 å·'


[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/flowbite/2.3.0/flowbite.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/wesome-qr/2.1.5-rc.0/awesome-qr.min.js'
[[params.foot.jsFile]]
    link = 'https://cdn.yangzupan.com/libs/html2canvas/html2canvas.min.js'
[[params.foot.jsFile]]
    link = ''